# Notes: Rebuild/Run this docker compose file:
#   sudo docker compose up -d --build --force-recreate

version: '3.9'

services:
  test-auto-docker-build:
    #build:
      #context: .
    #image: test-auto-docker-build
    image: ghcr.io/scadaguru/test-auto-docker-build:latest
    container_name: test-auto-docker-build
    volumes:
      - ./:/config
      - ./logs:/logs
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5001:5000
    restart: unless-stopped